title: Vaseem Shaik
description: Solar PV Engineer | Renewable Energy Specialist
theme: just-the-docs
plugins:
  - jekyll-feed

baseurl: ""
url: "https://yourgithubusername.github.io"

header:
  logo: /assets/images/logo.png

navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: Resume
    url: /resume
