title: "Vaseem Shaik"
description: "Solar PV Design Engineer | Electrical & Electronics Engineer | Rnewable Energy Engineer"
theme: jekyll-theme-cayman
image: "![Image](https://github.com/user-attachments/assets/2265147c-960d-4580-849a-1ac4e905b21e)"
