title: Vaseem Shaik
description: Electrical & Electronics Engineer | Solar PV Design Engineer | Renewable Energy Enthusiast
author: Vaseem Shaik
email: vmswork2@gmail.com
baseurl: ""
url: "https://yourusername.github.io"

theme: minima

linkedin_username: vms7-995501213
github_username: yourgithubusername

markdown: kramdown
